name: build

on:
  push:
    tags:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install packages
        run: pip install build pyinstaller

      - name: Build a binary wheel and a source tarball
        run: python -m build

      - name: Build an executable
        if: ${{ matrix.python-version == '3.9' }}
        run: pyinstaller asammdf.spec --distpath dist/${RUNNER_OS} --onefile

      # see: https://docs.github.com/en/actions/advanced-guides/storing-workflow-data-as-artifacts
      - name: Archive dist artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/
          if-no-files-found: error

