name: continuous integration

on: [push, pull_request]

jobs:
  test_and_build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install packages
        run: pip install tox tox-gh-actions coveralls build

      # see: https://github.com/ymyzk/tox-gh-actions
      - name: Run tox
        run: tox

      # see: https://coveralls-python.readthedocs.io/en/latest/usage/configuration.html#github-actions-support
      - name: Upload coverage data to coveralls.io
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.python-version == '3.7' }}
        run: coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # see: https://docs.github.com/en/actions/advanced-guides/storing-workflow-data-as-artifacts
      - name: Archive dist artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/
